/**
 * TodoBudget
 * API for Todo Budget app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Achievement model module.
 * @module model/Achievement
 * @version 1.0.0
 */
class Achievement {
    /**
     * Constructs a new <code>Achievement</code>.
     * @alias module:model/Achievement
     * @param name {String} 
     */
    constructor(name) { 
        
        Achievement.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['name'] = name;
    }

    /**
     * Constructs a <code>Achievement</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Achievement} obj Optional instance to populate.
     * @return {module:model/Achievement} The populated <code>Achievement</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Achievement();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('achieved')) {
                obj['achieved'] = ApiClient.convertToType(data['achieved'], 'Boolean');
            }
            if (data.hasOwnProperty('rewardAmount')) {
                obj['rewardAmount'] = ApiClient.convertToType(data['rewardAmount'], 'Number');
            }
            if (data.hasOwnProperty('rewardMessage')) {
                obj['rewardMessage'] = ApiClient.convertToType(data['rewardMessage'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
Achievement.prototype['name'] = undefined;

/**
 * has this been achieved
 * @member {Boolean} achieved
 */
Achievement.prototype['achieved'] = undefined;

/**
 * @member {Number} rewardAmount
 */
Achievement.prototype['rewardAmount'] = undefined;

/**
 * @member {String} rewardMessage
 */
Achievement.prototype['rewardMessage'] = undefined;






export default Achievement;

