/**
 * TodoBudget
 * API for Todo Budget app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Alert model module.
 * @module model/Alert
 * @version 1.0.0
 */
class Alert {
    /**
     * Constructs a new <code>Alert</code>.
     * @alias module:model/Alert
     * @param message {String} 
     */
    constructor(message) { 
        
        Alert.initialize(this, message);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, message) { 
        obj['message'] = message;
    }

    /**
     * Constructs a <code>Alert</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Alert} obj Optional instance to populate.
     * @return {module:model/Alert} The populated <code>Alert</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Alert();

            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('deterant')) {
                obj['deterant'] = ApiClient.convertToType(data['deterant'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} message
 */
Alert.prototype['message'] = undefined;

/**
 * @member {String} deterant
 */
Alert.prototype['deterant'] = undefined;






export default Alert;

