/**
 * TodoBudget
 * API for Todo Budget app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Profile model module.
 * @module model/Profile
 * @version 1.0.0
 */
class Profile {
    /**
     * Constructs a new <code>Profile</code>.
     * @alias module:model/Profile
     * @param name {String} Name of the user
     */
    constructor(name) { 
        
        Profile.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['name'] = name;
    }

    /**
     * Constructs a <code>Profile</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Profile} obj Optional instance to populate.
     * @return {module:model/Profile} The populated <code>Profile</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Profile();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('monthlySalary')) {
                obj['monthlySalary'] = ApiClient.convertToType(data['monthlySalary'], 'Number');
            }
            if (data.hasOwnProperty('insultLevel')) {
                obj['insultLevel'] = ApiClient.convertToType(data['insultLevel'], 'Number');
            }
            if (data.hasOwnProperty('financialKnowledgeLevel')) {
                obj['financialKnowledgeLevel'] = ApiClient.convertToType(data['financialKnowledgeLevel'], 'Number');
            }
            if (data.hasOwnProperty('happinessLevel')) {
                obj['happinessLevel'] = ApiClient.convertToType(data['happinessLevel'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Name of the user
 * @member {String} name
 */
Profile.prototype['name'] = undefined;

/**
 * amount of money made per month
 * @member {Number} monthlySalary
 */
Profile.prototype['monthlySalary'] = undefined;

/**
 * level of insults
 * @member {Number} insultLevel
 */
Profile.prototype['insultLevel'] = undefined;

/**
 * how smarticles the user in
 * @member {Number} financialKnowledgeLevel
 */
Profile.prototype['financialKnowledgeLevel'] = undefined;

/**
 * how good the user is doing
 * @member {Number} happinessLevel
 */
Profile.prototype['happinessLevel'] = undefined;






export default Profile;

